# Generated by Django 3.1 on 2021-05-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='medicines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_id', models.IntegerField(primary_key=0)),
                ('med_name', models.CharField(max_length=50)),
                ('med_price', models.IntegerField()),
                ('med_discount', models.IntegerField()),
                ('med_description', models.CharField(max_length=100)),
            ],
        ),
    ]
